/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

export interface Reddit {
  created?: string;
  id?: number;
  image?: string;
  name?: string;
  text?: string;
  url?: string;
  username?: string;
  username_url?: string;
}
