/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

export interface Twitch {
  created?: string;
  description?: string;
  external_id?: number;
  id?: number;
  language?: string;
  name?: string;
  published?: string;
  thumbnail?: string;
  view_count?: number;
}
