/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

export interface Youtube {
  channel_id?: string;
  channel_title?: string;
  comments_count?: number;
  created?: string;
  description?: string;
  dislike_count?: number;
  external_id?: string;
  favorite_count?: number;
  id?: number;
  like_count?: number;
  name?: string;
  thumbnails?: object;
  view_count?: number;
}
